from __future__ import annotations

# Shared assistant-audio policy used by runtime smoothing and offline capture analysis.

LEADING_SILENCE_TRIM_MAX_MS = 120
INTERCHUNK_LEADING_SILENCE_TRIM_MAX_MS = 60
INTERCHUNK_TRAILING_SILENCE_TRIM_MIN_MS = 20
INTERCHUNK_TRAILING_SILENCE_TRIM_MAX_MS = 30
INTERCHUNK_TRAILING_SILENCE_RMS_THRESHOLD = 96
INTERNAL_SILENCE_PRESERVE_MAX_MS = 400
FINAL_TRAILING_SILENCE_KEEP_MS = 140
LEADING_SILENCE_WINDOW_MS = 5
LEADING_SILENCE_PEAK_THRESHOLD = 48
LEADING_FADE_IN_MS = 4
CHUNK_GAP_WARNING_MS = 160
QUEUE_STARVATION_WARNING_MS = 40
QUEUE_BACKPRESSURE_WARNING_RATIO = 0.75
BOUNDARY_SMOOTH_MS = 3.0
BOUNDARY_JUMP_SMOOTH_ABS = 4_000
BOUNDARY_JUMP_WARNING_ABS = 8_000
ISOLATED_SPIKE_SMOOTH_ABS = 12_000

# Capture-analysis defaults reuse the runtime pause/click policy where the concerns overlap.
CAPTURE_ACTIVE_THRESHOLD = 24
CAPTURE_SILENCE_THRESHOLD = 8
CAPTURE_MAX_INTERNAL_SILENCE_MS = float(INTERNAL_SILENCE_PRESERVE_MAX_MS)
CAPTURE_EDGE_PADDING_MS = 60.0
CAPTURE_CONTEXT_WINDOW_MS = 10.0
CAPTURE_CONTEXT_ACTIVE_THRESHOLD = 32
CAPTURE_SILENCE_CONTEXT_RMS_THRESHOLD = 500.0
CAPTURE_VOICED_RMS_THRESHOLD = 200.0
CAPTURE_ROUGHNESS_THRESHOLD = 1.0
CAPTURE_ZERO_CROSSING_THRESHOLD = 0.35
CAPTURE_MAX_NOISY_FRAME_RATIO = 0.12
CAPTURE_CLICK_DERIVATIVE_THRESHOLD = float(ISOLATED_SPIKE_SMOOTH_ABS)
CAPTURE_CLICK_RMS_MULTIPLIER = 8.0
CAPTURE_MAX_CLICK_SPIKES_PER_SECOND = 0.5
